<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{c26bae5a-ff24-44e0-b6b0-bc4ad5ea9080}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	xInput : BOOL;
	xOutput : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[xOutput := xInput;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>